### PR TITLE
windows support

### PR DESCRIPTION
**Pull request by akansh97531**
@nikhilkumarsingh

### CODE REVIEW

**Comment by akansh97531** [comment]
@nikhilkumarsingh  found this library which support window too

**Comment by akansh97531** [comment]
@nikhilkumarsingh  should also run in macos

**Comment by nikhilkumarsingh** [comment]
@akansh97531  I tested your PR and found that clips are not getting copied to clipboard.
I am currently using Linux OS and using `ctrl` + `c` to copy text.

**Comment by akansh97531** [comment]
@nikhilkumarsingh please check now 
for both linux and windows

**Comment by nikhilkumarsingh** [comment]
1. No need to put `pprint` in `requirements.txt`  as its already in python library.
2. Put all new dependencies in `requirements.txt` and `install_requires` key of `setup.py`.

**Comment by akansh97531** [comment]
pynput added in install_requires

**Comment by akansh97531** [comment]
@nikhilkumarsingh fixing setup.py pep8 issues created some conflicts please review

**Pull request merged**
