### PR TITLE
Feature to set alternate key binding added

### PR DESCRIPTION
**Pull request by dibyadas**

### CODE REVIEW

**Comment by nikhilkumarsingh** [comment]
Nice work. But your code is not working on Python 2.
I get this error:
```
Traceback (most recent call last):
  File "clix.py", line 18, in <module>
    key_binding = pickle.load(f)
  File "/usr/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 892, in load_proto
    raise ValueError, "unsupported pickle protocol: %d" % proto
ValueError: unsupported pickle protocol: 3
```
Please fix it.

**Comment by dibyadas** [comment]
@nikhilkumarsingh  Done!  Does this look good?

**Comment by nikhilkumarsingh** [comment]
Yes it works fine now.
Only problem is the relative import of utils without using `.` prefix . Please fix it.
You can always check if your package is working fine or not by installing it on your system like this:
```
$ sudo pip install -U .
```
This will install local version and you can test it right away.

**Comment by dibyadas** [comment]
@nikhilkumarsingh  Thanks for the tip!  
I'm not really familiar with testing local packages using pip, hence the problem. I tried what you said but it seems the `config` file inside clix folder is not being included or something(?). I'll fix it and notify you as soon as I can.

**Comment by nikhilkumarsingh** [comment]
You will need to include config in [MANIFEST.in](https://github.com/coding-blocks/clix/blob/master/MANIFEST.in).

**Comment by dibyadas** [comment]
@nikhilkumarsingh Fixed the pip error. Thanks again for the tip!

**Comment by nikhilkumarsingh** [comment]
Have you tested the local version for Python 2 as well as Python 3?
Is it working in all aspects?

**Comment by dibyadas** [comment]
It did work for me. If you meant installing through pip (Python 2.7) , I haven't done that. Although running in Python 3 and 2 did not cause any problem..

**Pull request merged**
