### PR TITLE
async. gui

### PR DESCRIPTION
**Pull request by akansh97531**
@nikhilkumarsingh

### CODE REVIEW

**Comment by nikhilkumarsingh** [comment]
Fix all the pep8 issues.

**Comment by akansh97531** [comment]
@nikhilkumarsingh

**Comment by akansh97531** [comment]
@nikhilkumarsingh please review and also see issue #13

**Comment by akansh97531** [comment]
@nikhilkumarsingh please review

**Comment by nikhilkumarsingh** [comment]
I am not able to make more than 1 clip. This is the error I get:
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/clix/pyxhook.py", line 138, in run
    self.record_dpy.record_enable_context(self.ctx, self.processevents)
  File "/usr/lib/python2.7/dist-packages/Xlib/ext/record.py", line 238, in enable_context
    context = context)
  File "/usr/lib/python2.7/dist-packages/Xlib/ext/record.py", line 215, in __init__
    rq.ReplyRequest.__init__(self, *args, **keys)
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/rq.py", line 1478, in __init__
    self.reply()
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/rq.py", line 1490, in reply
    self._display.send_and_recv(request = self._serial)
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/display.py", line 556, in send_and_recv
    gotreq = self.parse_response(request)
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/display.py", line 643, in parse_response
    gotreq = self.parse_request_response(request) or gotreq
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/display.py", line 729, in parse_request_response
    req._parse_response(self.data_recv[:self.request_length])
  File "/usr/lib/python2.7/dist-packages/Xlib/ext/record.py", line 219, in _parse_response
    self._callback(r)
  File "/usr/local/lib/python2.7/dist-packages/clix/pyxhook.py", line 190, in processevents
    self.KeyDown(hookevent)
  File "/usr/local/lib/python2.7/dist-packages/clix/clix.py", line 66, in OnKeyPress
    'clips_data'), "wb") as f:
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/clix/clips_data'
```

**Comment by nikhilkumarsingh** [comment]
nice work @akansh97531 
@championswimmer please assign bounty points.

**Pull request merged**
