### PR TITLE
Add windows support

### PR DESCRIPTION
**Pull request by prateekiiest**
PyHook is the library in windows.

Issue #3

### CODE REVIEW

**Comment by nikhilkumarsingh** [comment]
1. What is the use of pyhook.py? (You are not even importing it)

2. I tried your patch on windows 10 (64-bit) and got following error:
```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pyHook\HookManager.py", line 351, in KeyboardSwitch
    return func(event)
  File "clix.py", line 59, in OnKeyPress
    clipboard(clips)
  File "C:\Users\Nikhil\Desktop\clix-2\clix\clix\gui.py", line 21, in __init__
    self.root = Tk()
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 1679, in __init__
    import sys, os
TypeError: an integer is required
```

**Comment by prateekiiest** [comment]
Maybe for future use, we may require pyhook.
For the time being, I am removing it.

**Comment by prateekiiest** [comment]
@nikhilkumarsingh , are you getting the same error?

**Comment by championswimmer** [comment]
@nikhilkumarsingh please review

**Comment by nikhilkumarsingh** [comment]
We are already working on this issue in #6 . This thread has been inactive for a long time. @prateekiiest you can refer to #6 and fix some bugs there.

**Pull request closed without merging**
